// Copyright 2026 The FlutterWatch Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/// Builds `PORTING_REPORT.md` for an FFI scaffold: it explains the watchOS
/// FFI plugin model and lists the iOS/macOS APIs the source plugin used
/// (detected against the compatibility database) with their watchOS status,
/// so the developer knows which functions to implement in the C stub and
/// which capabilities have no watchOS equivalent.
library;

import 'compatibility_database.dart';
import 'porting_result.dart';
import 'source_analyzer.dart';

/// Stateless renderer. Pure function of its inputs so it golden-tests
/// cleanly; inject `today` in tests to keep output deterministic.
class ReportEmitter {
  const ReportEmitter();

  /// Renders the `PORTING_REPORT.md` body for [source] given the
  /// compatibility [findings] collected from the source's native code.
  String render({
    required PluginSource source,
    required List<PortingFinding> findings,
    String? today,
  }) {
    // Group findings by API name; each API keeps its note and one example
    // source location.
    final byApi = <String, _ApiUse>{};
    for (final f in findings) {
      byApi.putIfAbsent(f.pattern.name, () => _ApiUse(f.pattern))
          .locations
          .add('${f.fileRelativePath}:${f.line}');
    }
    final unsupported = <_ApiUse>[
      for (final _ApiUse u in byApi.values)
        if (u.pattern.severity == Severity.unsupported) u,
    ]..sort((a, b) => a.pattern.name.compareTo(b.pattern.name));
    final partial = <_ApiUse>[
      for (final _ApiUse u in byApi.values)
        if (u.pattern.severity != Severity.unsupported) u,
    ]..sort((a, b) => a.pattern.name.compareTo(b.pattern.name));

    final b = StringBuffer()
      ..writeln('# ${source.outputPackageName} — porting report')
      ..writeln()
      ..writeln('Generated by `flutter-watchos plugin port` on ${today ?? _today()}.')
      ..writeln()
      ..writeln('Source: `${source.packageName}` ${source.sourceVersion ?? '(no version)'} '
          '(path: `${source.directory.path}`)')
      ..writeln('Base platform: ${source.sourcePlatform} (${_languageLabel(source)})')
      ..writeln('Output: `./${source.outputPackageName}`')
      ..writeln();

    b
      ..writeln('## This is an FFI scaffold')
      ..writeln()
      ..writeln('Method-channel plugins are not supported on watchOS — a '
          '`pluginClass:`-only implementation builds, but its channel calls '
          'throw `MissingPluginException`. The supported plugin model is '
          '**dart:ffi**, so this package is an FFI scaffold, not a copy '
          "of the source plugin's native code:")
      ..writeln()
      ..writeln('- `watchos/Classes/${source.outputPackageName}_ffi.{h,m}` — the C '
          'functions to implement (one example symbol is provided so the '
          'package builds and links immediately).')
      ..writeln('- `watchos/Package.swift` — the FFI manifest; add the frameworks '
          'your C code links.')
      ..writeln('- `lib/${source.outputPackageName}.dart` — the Dart class over the '
          'platform interface; resolve each C symbol via '
          '`DynamicLibrary.process()` and override the interface methods.')
      ..writeln('- `pubspec.yaml` — declares `ffiPlugin: true` and lists your '
          'exported symbols under `ffiSymbols` (the CLI force-references each '
          'so it survives the static link).')
      ..writeln();

    b
      ..writeln('## APIs the source plugin used')
      ..writeln();
    if (findings.isEmpty) {
      b
        ..writeln('No compatibility-database APIs were detected in the source '
            '(it may be pure-Dart, Pigeon-generated, or FFI already). '
            "Implement the plugin's capability directly against WatchKit / "
            'Foundation.')
        ..writeln();
    } else {
      if (unsupported.isNotEmpty) {
        b
          ..writeln('### Not available on watchOS')
          ..writeln()
          ..writeln('These iOS/macOS APIs have **no watchOS equivalent** — the '
              'capability must be omitted or redesigned (often via the paired '
              'iPhone):')
          ..writeln()
          ..writeln('| API | Used at | Why / watchOS note |')
          ..writeln('|---|---|---|');
        for (final u in unsupported) {
          b.writeln('| ${u.pattern.name} | ${u.locationSummary} | ${_collapse(u.pattern.note)} |');
        }
        b.writeln();
      }
      if (partial.isNotEmpty) {
        b
          ..writeln('### Available, but review')
          ..writeln()
          ..writeln('These work on watchOS (often differently than iOS) — '
              'implement them, checking the note:')
          ..writeln()
          ..writeln('| API | Used at | watchOS note |')
          ..writeln('|---|---|---|');
        for (final u in partial) {
          b.writeln('| ${u.pattern.name} | ${u.locationSummary} | ${_collapse(u.pattern.note)} |');
        }
        b.writeln();
      }
    }

    b
      ..writeln('## Checklist')
      ..writeln()
      ..writeln('- [ ] Declare your C functions in '
          '`watchos/Classes/${source.outputPackageName}_ffi.h` and implement '
          'them in the `.m`, one per platform-interface method you support.')
      ..writeln('- [ ] List every exported symbol under `ffiSymbols` in '
          '`pubspec.yaml`, and the frameworks you link in `Package.swift`.')
      ..writeln('- [ ] Add a `lookupFunction` binding per symbol in the Dart '
          '`Bindings` class and override the platform-interface methods.')
      ..writeln('- [ ] Add the package to a watchOS app (`flutter-watchos '
          'create` one if needed), build for `watchsimulator`, then `nm` the '
          'binary to confirm your `ffiSymbols` are present (type `T`).')
      ..writeln('- [ ] Bump the version and update `CHANGELOG.md` before '
          'publishing.')
      ..writeln()
      ..writeln('---')
      ..writeln()
      ..writeln('See the finished plugins in the `flutterwatch/plugins` repo '
          '(e.g. `path_provider_watchos`, `battery_plus_watchos`) for worked '
          'examples of this exact shape.');

    return b.toString();
  }

  String _collapse(String note) =>
      note.replaceAll('\n', ' ').replaceAll(RegExp(r' {2,}'), ' ').trim();

  String _languageLabel(PluginSource source) => switch (source.sourceLanguage) {
        SourceLanguage.swift => 'Swift',
        SourceLanguage.objc => 'Objective-C',
        SourceLanguage.mixed => 'Swift + Objective-C',
        SourceLanguage.unknown => 'unknown',
      };

  static String _today() {
    final now = DateTime.now();
    final String yyyy = now.year.toString().padLeft(4, '0');
    final String mm = now.month.toString().padLeft(2, '0');
    final String dd = now.day.toString().padLeft(2, '0');
    return '$yyyy-$mm-$dd';
  }
}

/// One compatibility-database API the source plugin used, with every source
/// location it appeared at.
class _ApiUse {
  _ApiUse(this.pattern);
  final ApiPattern pattern;
  final List<String> locations = <String>[];

  /// The first location, plus a `(+N more)` suffix when there are others.
  String get locationSummary {
    if (locations.isEmpty) {
      return '—';
    }
    final first = '`${locations.first}`';
    return locations.length == 1 ? first : '$first (+${locations.length - 1} more)';
  }
}
