// Copyright 2026 The FlutterWatch Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Templates start with `$header` (an already-rendered comment block) rather
// than a literal newline. The `leading_newlines_in_multiline_strings` lint
// would force us to insert a blank line between the file header and the
// first line of code in the rendered output, which we don't want.
// ignore_for_file: leading_newlines_in_multiline_strings

/// Inline templates for the `flutter-watchos plugin port` scaffolder.
///
/// The porter emits an **FFI** scaffold, not a method-channel plugin —
/// method-channel plugins are not supported on watchOS, so native plugin
/// code is only reachable through `dart:ffi`.
/// A ported package therefore exports C symbols from `watchos/Classes/`, the
/// CLI force-loads the compiled archive into the watch binary, and the Dart
/// side resolves the symbols via `DynamicLibrary.process()`. This mirrors
/// the first-party `flutter_watchos` package and the finished plugins in the
/// `flutterwatch/plugins` repo.
///
/// These are Dart strings rather than `.tmpl` files so the porter has zero
/// runtime dependency on the package's own asset layout. Interpolation is
/// plain Dart `${...}` so the templates are lintable and refactorable.
library;

import 'source_analyzer.dart';

/// Default copyright holder line baked into generated source files when the
/// caller doesn't override it via `--license-holder`.
const String kDefaultLicenseHolder = 'The FlutterWatch Authors';

/// Minimum watchOS version the generated `Package.swift` declares. Matches
/// the SwiftPM floor the flutter-watchos build system uses for the
/// FlutterFramework package.
const String kMinimumWatchosVersion = '7.0';

/// The example C symbol the scaffold ships, e.g.
/// `battery_plus_watchos_example`. Both the C stub and the pubspec's
/// `ffiSymbols` list reference it, so a freshly ported package builds and
/// links before the developer has written any real functions.
String exampleSymbolName(PluginSource source) =>
    '${source.outputPackageName}_example';

/// PascalCase Dart implementation class, e.g. `BatteryPlusWatchos`.
String dartClassName(PluginSource source) =>
    _pascalCase(source.outputPackageName);

/// The Bindings class name, e.g. `BatteryPlusWatchosBindings`.
String bindingsClassName(PluginSource source) => '${dartClassName(source)}Bindings';

/// Renders the BSD-3-style header that goes at the top of every generated
/// source file (Dart, C, Package.swift, README).
String renderLicenseHeader({
  required String holder,
  required String commentPrefix,
  String? sourcePlugin,
}) {
  final String today = _today();
  final lines = <String>[
    'Copyright 2026 $holder. All rights reserved.',
    'Use of this source code is governed by a BSD-style license that can be',
    'found in the LICENSE file.',
    '',
    'Generated on $today by `flutter-watchos plugin port`.',
    if (sourcePlugin != null) 'Source plugin: $sourcePlugin',
  ];
  return lines.map((String l) => l.isEmpty ? commentPrefix.trim() : '$commentPrefix$l').join('\n');
}

/// Renders the output package's `pubspec.yaml` — an FFI plugin declaration.
String renderPubspec({required PluginSource source, required String licenseHolder}) {
  final String description = _quoteForYaml(
    'watchOS implementation of ${source.basePackageName} (dart:ffi).',
  );
  const homepage = 'https://github.com/flutterwatch/plugins';
  final String? platformInterface = source.platformInterfacePackage;
  final String dartClass = dartClassName(source);
  final buf = StringBuffer()
    ..writeln('name: ${source.outputPackageName}')
    ..writeln('description: $description')
    ..writeln('version: 0.0.1')
    ..writeln('homepage: $homepage')
    ..writeln('# Generated by `flutter-watchos plugin port`. See PORTING_REPORT.md.')
    ..writeln('# License holder: $licenseHolder')
    ..writeln()
    ..writeln('environment:')
    ..writeln('  sdk: ">=3.0.0 <4.0.0"')
    ..writeln('  flutter: ">=3.13.0"')
    ..writeln()
    ..writeln('dependencies:')
    ..writeln('  ffi: ^2.1.0')
    ..writeln('  flutter:')
    ..writeln('    sdk: flutter');
  if (platformInterface != null) {
    final String raw = source.platformInterfaceConstraint ?? 'any';
    final bool needsQuote = RegExp(r'[>< ]').hasMatch(raw);
    final constraint =
        needsQuote ? '"${raw.replaceAll('"', r'\"')}"' : raw;
    buf.writeln('  $platformInterface: $constraint');
  }
  buf
    ..writeln()
    ..writeln('dev_dependencies:')
    ..writeln('  flutter_lints: ^4.0.0')
    ..writeln('  flutter_test:')
    ..writeln('    sdk: flutter')
    ..writeln()
    ..writeln('flutter:')
    ..writeln('  plugin:');
  if (platformInterface != null) {
    buf.writeln('    implements: ${source.basePackageName}');
  }
  buf
    ..writeln('    platforms:')
    ..writeln('      watchos:')
    ..writeln('        # FFI plugin: the CLI compiles watchos/Classes/*.m into a')
    ..writeln('        # static archive force-loaded into the watch binary; Dart')
    ..writeln('        # resolves the exported symbols via DynamicLibrary.process().')
    ..writeln('        # Method-channel plugins are not supported on watchOS,')
    ..writeln('        # so this is the supported plugin model.')
    ..writeln('        ffiPlugin: true')
    ..writeln('        dartPluginClass: $dartClass')
    ..writeln('        # C symbols exported for dart:ffi lookup. The CLI emits a')
    ..writeln('        # forced reference for each so they survive the static link.')
    ..writeln('        # TODO(porter): list every C function you export here.')
    ..writeln('        ffiSymbols:')
    ..writeln('          - ${exampleSymbolName(source)}');
  return buf.toString();
}

/// Renders the C header stub at `watchos/Classes/<pkg>_ffi.h`.
String renderFfiHeader({required PluginSource source, required String licenseHolder}) {
  final String header = renderLicenseHeader(
    holder: licenseHolder,
    commentPrefix: '// ',
    sourcePlugin: source.packageName,
  );
  final guard = '${source.outputPackageName.toUpperCase()}_FFI_H';
  final exportMacro = '${source.outputPackageName.toUpperCase()}_EXPORT';
  return '''$header

#ifndef $guard
#define $guard

// Each exported symbol is marked `used` + default-visibility so it survives
// the linker's `-dead_strip` and lands in the executable's dynamic symbol
// table, where `DynamicLibrary.process()` / dlsym can resolve it. The watch
// app links this archive statically, so without the attributes the linker
// would drop these (FFI has no compile-time caller). The CLI additionally
// emits a forced reference for each symbol listed under
// `flutter.plugin.platforms.watchos.ffiSymbols`.
#define $exportMacro \\
  __attribute__((visibility("default"))) __attribute__((used))

// TODO(porter): declare one C function per platform-interface method your
// plugin needs. Return C scalars (int32_t/int64_t/double/bool) or UTF-8 C
// strings (const char*, owned by the plugin — never freed by Dart). See the
// finished plugins in flutterwatch/plugins for worked examples.
$exportMacro const char* ${exampleSymbolName(source)}(void);

#endif  // $guard
''';
}

/// Renders the C source stub at `watchos/Classes/<pkg>_ffi.m`.
String renderFfiSource({required PluginSource source, required String licenseHolder}) {
  final String header = renderLicenseHeader(
    holder: licenseHolder,
    commentPrefix: '// ',
    sourcePlugin: source.packageName,
  );
  return '''$header

#import "${source.outputPackageName}_ffi.h"

#import <Foundation/Foundation.h>
#import <WatchKit/WatchKit.h>

// TODO(porter): implement your exported functions using WatchKit / Foundation
// (and the frameworks you declared in Package.swift). Map each
// platform-interface method to a watchOS API — see PORTING_REPORT.md for the
// APIs the source plugin used on iOS and their watchOS equivalents.
const char* ${exampleSymbolName(source)}(void) {
  return "";
}
''';
}

/// Renders `watchos/Package.swift` — an FFI plugin manifest.
///
/// The flutter-watchos CLI discovers the plugin through this file, compiles
/// `Classes/*.m` into a static archive force-loaded into the watch binary,
/// and links every `.linkedFramework(...)` declared here.
String renderPackageSwift({required PluginSource source}) {
  final String name = source.outputPackageName;
  final String libraryName = name.replaceAll('_', '-');
  return '''// swift-tools-version:5.9
// Generated by `flutter-watchos plugin port`. Do not edit by hand.
//
// FFI plugin manifest. The flutter-watchos CLI discovers the plugin through
// this file, compiles `Classes/*.m` into a static archive force-loaded into
// the watch binary, and links the frameworks declared below.
import PackageDescription

let package = Package(
    name: "$name",
    platforms: [
        .watchOS("$kMinimumWatchosVersion"),
    ],
    products: [
        .library(name: "$libraryName", targets: ["$name"]),
    ],
    targets: [
        .target(
            name: "$name",
            path: "Classes",
            publicHeadersPath: ".",
            cSettings: [
                .headerSearchPath("."),
            ],
            linkerSettings: [
                .linkedFramework("Foundation"),
                // TODO(porter): add the frameworks your C code links, e.g.
                // WatchKit, CoreLocation, CoreMotion, Network.
                .linkedFramework("WatchKit"),
            ]
        ),
    ]
)
''';
}

/// Renders the Dart entry point at `lib/<pkg>.dart`: an FFI bindings class
/// plus a platform-interface implementation that resolves the native symbols
/// via `DynamicLibrary.process()`.
String renderDartEntry({required PluginSource source, required String licenseHolder}) {
  final String header = renderLicenseHeader(
    holder: licenseHolder,
    commentPrefix: '// ',
    sourcePlugin: source.packageName,
  );
  final String dartClass = dartClassName(source);
  final String bindings = bindingsClassName(source);
  final String exampleSymbol = exampleSymbolName(source);
  final String? interface = source.platformInterfacePackage;

  // The generated class deliberately does NOT `extends` the platform
  // interface: the interface class name can't be guessed reliably (e.g.
  // `sensors_plus` federates through `SensorsPlatform`, not
  // `SensorsPlusPlatform`), and a wrong name would stop the scaffold from
  // compiling. Instead the class is standalone so a freshly ported package
  // builds and links immediately — proving the whole FFI pipeline — and the
  // federated wiring is shown as a ready-to-apply TODO block below.
  final wiringTodo = StringBuffer();
  if (interface != null) {
    final String platformClass = _platformInterfaceClassName(interface);
    wiringTodo
      ..writeln('// TODO(porter): make this the federated `${source.basePackageName}`')
      ..writeln('// implementation. Add the import, `extends` the platform interface,')
      ..writeln('// and set the instance in registerWith(). The interface class is')
      ..writeln('// guessed as `$platformClass` — verify it against')
      ..writeln('// package:$interface.')
      ..writeln('//')
      ..writeln("//   import 'package:$interface/$interface.dart';")
      ..writeln('//')
      ..writeln('//   class $dartClass extends $platformClass {')
      ..writeln('//     static void registerWith() {')
      ..writeln('//       $platformClass.instance = $dartClass();')
      ..writeln('//     }')
      ..writeln('//     // ...override the interface methods, forwarding to `b`.')
      ..writeln('//   }');
  } else {
    wiringTodo
      ..writeln('// This plugin declares no federated platform interface; wire')
      ..writeln('// registerWith() to whatever entry point your app expects.');
  }

  return '''$header
//
// watchOS implementation of `${source.basePackageName}`, over dart:ffi.
//
// `watchos/Classes/${source.outputPackageName}_ffi.m` exports C symbols; the
// CLI force-loads the compiled archive into the watch binary and this class
// resolves them via `DynamicLibrary.process()`.

import 'dart:ffi';

import 'package:ffi/ffi.dart';

/// watchOS implementation of `${source.basePackageName}`.
$wiringTodo
class $dartClass {
  /// Test hook: set before first use to replace the FFI bindings.
  static $bindings? bindingsOverride;

  static $bindings? _bindings;

  /// The FFI bindings (or the test override).
  static $bindings get b =>
      bindingsOverride ?? (_bindings ??= $bindings());

  /// Registers this implementation. TODO(porter): set the platform-interface
  /// instance here (see the wiring note above).
  static void registerWith() {}
}

/// FFI bindings to the native ${source.outputPackageName} C functions.
///
/// Overridable for tests via [$dartClass.bindingsOverride]; the
/// [$bindings.forTesting] constructor skips FFI initialization so fakes work
/// off-device.
class $bindings {
  /// Creates bindings that look up native symbols in the current process.
  $bindings() : _lib = DynamicLibrary.process();

  /// Constructor for fakes/mocks — skips FFI initialization.
  $bindings.forTesting() : _lib = null;

  final DynamicLibrary? _lib;

  // TODO(porter): add one late-bound function per exported C symbol, e.g.
  //   late final int Function() foo =
  //       _lib!.lookupFunction<Int32 Function(), int Function()>('..._foo');
  late final Pointer<Utf8> Function() _example = _lib!
      .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
          '$exampleSymbol');

  /// Example binding — replace with your plugin's real getters.
  String get example {
    final Pointer<Utf8> p = _example();
    return p == nullptr ? '' : p.toDartString();
  }
}
''';
}

/// Renders a placeholder test that references the generated class so the
/// package compiles and `dart test` is green out of the box.
String renderTestStub({required PluginSource source, required String licenseHolder}) {
  final String header = renderLicenseHeader(
    holder: licenseHolder,
    commentPrefix: '// ',
    sourcePlugin: source.packageName,
  );
  final String dartClass = dartClassName(source);
  return '''$header

import 'package:flutter_test/flutter_test.dart';
import 'package:${source.outputPackageName}/${source.outputPackageName}.dart';

void main() {
  test('package compiles and exposes $dartClass', () {
    expect($dartClass, isNotNull);
  });
}
''';
}

/// Renders the README that ships with the generated package.
String renderReadme({required PluginSource source, required String licenseHolder}) {
  final interfaceNote = source.platformInterfacePackage != null
      ? 'This is a federated plugin implementation. Apps that already depend '
          'on `${source.basePackageName}` and target watchOS only need to add '
          'this package alongside it:'
      : 'Add this package to your app to use it on watchOS:';
  return '''# ${source.outputPackageName}

The watchOS implementation of [`${source.basePackageName}`](https://pub.dev/packages/${source.basePackageName}).

> Scaffolded by [`flutter-watchos plugin port`](https://github.com/flutterwatch/flutter-watchos)
> from `${source.packageName}` as an **FFI** plugin. Read `PORTING_REPORT.md`,
> then implement the C functions in `watchos/Classes/` and the Dart methods
> in `lib/`.

## Usage

$interfaceNote

```yaml
dependencies:
  ${source.basePackageName}: ^<latest>
  ${source.outputPackageName}: ^0.0.1
```

## Status

🚧 Scaffold — the FFI bindings compile and link, but the exported functions
are stubs. See `PORTING_REPORT.md` for the APIs to implement.

## License

$licenseHolder under a BSD-3-Clause license. See `LICENSE` for the full text.
''';
}

/// Renders a CHANGELOG seed.
String renderChangelog({required PluginSource source}) {
  return '''## 0.0.1

* Initial watchOS FFI scaffold generated by `flutter-watchos plugin port`
  from `${source.packageName}`.
''';
}

/// Renders a tight, focused `analysis_options.yaml`.
String renderAnalysisOptions() {
  return '''
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
''';
}

/// Renders a `.gitignore` covering the standard Dart/Flutter outputs plus the
/// SwiftPM build state that shows up under `watchos/`.
String renderGitignore() {
  return '''
# Dart / Flutter
.dart_tool/
build/
.flutter-plugins
.flutter-plugins-dependencies
.packages
.pub/

# Xcode / SwiftPM (per-user, generated when watchos/Package.swift is opened)
**/.swiftpm/
**/.build/
**/xcuserdata/

# IDE
.idea/
.vscode/
*.iml

# macOS
.DS_Store
''';
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

String _today() {
  final now = DateTime.now();
  final String yyyy = now.year.toString().padLeft(4, '0');
  final String mm = now.month.toString().padLeft(2, '0');
  final String dd = now.day.toString().padLeft(2, '0');
  return '$yyyy-$mm-$dd';
}

String _quoteForYaml(String s) {
  final String escaped = s.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
  return '"$escaped"';
}

/// `battery_plus_watchos` → `BatteryPlusWatchos`.
String _pascalCase(String name) => name
    .split('_')
    .where((String p) => p.isNotEmpty)
    .map((String p) => p[0].toUpperCase() + p.substring(1))
    .join();

/// `url_launcher_platform_interface` → `UrlLauncherPlatform`.
///
/// Best-effort heuristic: drops the `_platform_interface` suffix, then
/// upper-CamelCases the rest, then appends `Platform`. The generated Dart
/// tells the developer to adjust it if the real class differs.
String _platformInterfaceClassName(String interfacePackage) {
  var base = interfacePackage;
  if (base.endsWith('_platform_interface')) {
    base = base.substring(0, base.length - '_platform_interface'.length);
  }
  return '${_pascalCase(base)}Platform';
}
