// Copyright 2026 The FlutterWatch Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter_tools/src/base/common.dart';
import 'package:flutter_tools/src/base/file_system.dart';
import 'package:flutter_tools/src/base/logger.dart';
import 'package:flutter_tools/src/base/process.dart';
import 'package:meta/meta.dart';

/// App Store packaging for standalone (watch-only) apps.
///
/// Xcode 26 removed App Store distribution of watch-only archives from
/// `xcodebuild -exportArchive` (only ad-hoc/enterprise/development methods are
/// offered) — the store packaging that Xcode Organizer performs interactively
/// is reproduced here instead, which is what makes a fully scripted
/// `flutter-watchos build ipa && flutter-watchos upload` possible.
///
/// A watch-only App Store package is an **iOS container** app:
///
/// ```text
/// Payload/<AppName>.app/            iOS stub (no UI, never launched)
///   Info.plist                      ITSWatchOnlyContainer + LSApplicationLaunchProhibited
///   <stub binary>                   minimal arm64 iOS executable
///   embedded.mobileprovision        App Store profile for <container-id>
///   Watch/Runner.app                the real watch app
///     Info.plist                    CFBundleIdentifier = <container-id>.watchkitapp
///     embedded.mobileprovision      App Store profile for <container-id>.watchkitapp
/// ```
///
/// The container's bundle id is the App Store Connect record; the embedded
/// watch app always uses `<container-id>.watchkitapp` (matching what Xcode
/// Organizer generates), regardless of which of the two forms the Xcode
/// project itself uses. Every plist key in [containerInfoPlistXml] was
/// dictated by App Store Connect validation errors — change with care and
/// re-validate with `flutter-watchos upload --validate-only`.

/// The App Store Connect record id for a watch app project bundle id: the
/// project may use either `com.acme.app` or `com.acme.app.watchkitapp`.
String containerBundleIdFor(String projectBundleId) {
  const suffix = '.watchkitapp';
  return projectBundleId.endsWith(suffix)
      ? projectBundleId.substring(0, projectBundleId.length - suffix.length)
      : projectBundleId;
}

/// The bundle id the embedded watch app must carry inside the store package.
String watchBundleIdFor(String projectBundleId) {
  return '${containerBundleIdFor(projectBundleId)}.watchkitapp';
}

String _xmlEscape(String s) => s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');

/// The Info.plist of the watch-only iOS container.
///
/// Keys are the minimum set App Store Connect validation accepts for a
/// watch-only submission (each one below was demanded by a 409 validation
/// error when absent):
///  - `ITSWatchOnlyContainer` + `LSApplicationLaunchProhibited`: required
///    when the embedded watch app has `WKWatchOnly = true`.
///  - `UIRequiredDeviceCapabilities [arm64]`: required for the 64-bit stub.
///  - `UIDeviceFamily [1, 2]`: store packages generated by Xcode Organizer
///    declare iPhone + iPad; declaring fewer families than a previously
///    shipped version is rejected ("must continue to support all devices").
///  - `DT*` / `BuildMachineOSBuild`: toolchain stamps; without them the
///    upload is rejected as built with an "unsupported SDK or Xcode".
String containerInfoPlistXml({
  required String appName,
  required String bundleId,
  required String shortVersion,
  required String buildNumber,
  required String executableName,
  required Map<String, String> toolchainStamps,
}) {
  final stamps = StringBuffer();
  final List<String> stampKeys = toolchainStamps.keys.toList()..sort();
  for (final key in stampKeys) {
    stamps.writeln(
        '\t<key>${_xmlEscape(key)}</key><string>${_xmlEscape(toolchainStamps[key]!)}</string>');
  }
  return '''
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
\t<key>CFBundleDevelopmentRegion</key><string>en</string>
\t<key>CFBundleDisplayName</key><string>${_xmlEscape(appName)}</string>
\t<key>CFBundleExecutable</key><string>${_xmlEscape(executableName)}</string>
\t<key>CFBundleIdentifier</key><string>${_xmlEscape(bundleId)}</string>
\t<key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
\t<key>CFBundleName</key><string>${_xmlEscape(appName)}</string>
\t<key>CFBundlePackageType</key><string>APPL</string>
\t<key>CFBundleShortVersionString</key><string>${_xmlEscape(shortVersion)}</string>
\t<key>CFBundleSupportedPlatforms</key><array><string>iPhoneOS</string></array>
\t<key>CFBundleVersion</key><string>${_xmlEscape(buildNumber)}</string>
\t<key>ITSWatchOnlyContainer</key><true/>
\t<key>LSApplicationLaunchProhibited</key><true/>
\t<key>MinimumOSVersion</key><string>15.0</string>
\t<key>UIDeviceFamily</key><array><integer>1</integer><integer>2</integer></array>
\t<key>UIRequiredDeviceCapabilities</key><array><string>arm64</string></array>
${stamps.toString().trimRight()}
</dict>
</plist>
''';
}

/// A parsed provisioning profile, as far as store packaging cares.
@immutable
class ProvisioningProfileInfo {
  const ProvisioningProfileInfo({
    required this.path,
    required this.name,
    required this.appId,
    required this.isAppStore,
    required this.expiresAt,
  });

  final String path;
  final String name;

  /// The bundle id the profile provisions (application-identifier minus the
  /// team prefix). `*` for wildcard profiles.
  final String appId;

  /// True for App Store distribution profiles: no device list and
  /// `get-task-allow = false`.
  final bool isAppStore;

  final DateTime? expiresAt;
}

/// Picks the best App Store profile for [bundleId]: exact app-id match,
/// unexpired, latest expiry wins.
ProvisioningProfileInfo? selectStoreProfile(
  List<ProvisioningProfileInfo> profiles,
  String bundleId, {
  DateTime? now,
}) {
  final DateTime cutoff = now ?? DateTime.now();
  final List<ProvisioningProfileInfo> candidates = profiles
      .where((ProvisioningProfileInfo p) =>
          p.isAppStore &&
          p.appId == bundleId &&
          (p.expiresAt == null || p.expiresAt!.isAfter(cutoff)))
      .toList()
    ..sort((ProvisioningProfileInfo a, ProvisioningProfileInfo b) {
      final DateTime ax = a.expiresAt ?? DateTime(9999);
      final DateTime bx = b.expiresAt ?? DateTime(9999);
      return bx.compareTo(ax);
    });
  return candidates.isEmpty ? null : candidates.first;
}

/// Orchestrates archive → re-sign → container synthesis → .ipa.
///
/// Everything here shells out to Apple tooling (`xcodebuild`, `codesign`,
/// `security`, `plutil`, `PlistBuddy`, `clang`, `zip`) — the pure decisions
/// live in the top-level helpers above so they stay unit-testable.
class WatchosIpaPackager {
  WatchosIpaPackager({
    required FileSystem fileSystem,
    required Logger logger,
    required ProcessUtils processUtils,
    required String homeDirPath,
  })  : _fs = fileSystem,
        _logger = logger,
        _processUtils = processUtils,
        _home = homeDirPath;

  final FileSystem _fs;
  final Logger _logger;
  final ProcessUtils _processUtils;
  final String _home;

  static const String _plistBuddy = '/usr/libexec/PlistBuddy';

  Future<RunResult> _run(List<String> cmd) => _processUtils.run(cmd);

  Future<String> _runOrExit(List<String> cmd, String what) async {
    final RunResult result = await _run(cmd);
    if (result.exitCode != 0) {
      throwToolExit('$what failed:\n${result.stderr}\n${result.stdout}');
    }
    return result.stdout.trim();
  }

  Future<String> _plutilRaw(String keyPath, String plistPath) =>
      _runOrExit(<String>['plutil', '-extract', keyPath, 'raw', '-o', '-', plistPath],
          'Reading $keyPath from $plistPath');

  /// The provisioning-profile directories Xcode uses (new location first).
  List<Directory> profileDirectories() => <Directory>[
        _fs.directory(_fs.path.join(
            _home, 'Library', 'Developer', 'Xcode', 'UserData', 'Provisioning Profiles')),
        _fs.directory(
            _fs.path.join(_home, 'Library', 'MobileDevice', 'Provisioning Profiles')),
      ];

  /// Decodes and indexes every local provisioning profile.
  Future<List<ProvisioningProfileInfo>> scanProfiles(Directory scratch) async {
    final profiles = <ProvisioningProfileInfo>[];
    for (final Directory dir in profileDirectories()) {
      if (!dir.existsSync()) {
        continue;
      }
      for (final FileSystemEntity entity in dir.listSync()) {
        if (entity is! File || !entity.path.endsWith('.mobileprovision')) {
          continue;
        }
        final File decoded = scratch.childFile('${entity.basename}.plist');
        final RunResult decode =
            await _run(<String>['security', 'cms', '-D', '-i', entity.path, '-o', decoded.path]);
        if (decode.exitCode != 0 || !decoded.existsSync()) {
          continue; // Unreadable profile — skip, never fatal.
        }
        try {
          final String name = await _plutilRaw('Name', decoded.path);
          final String appIdFull =
              await _plutilRaw('Entitlements.application-identifier', decoded.path);
          // "TEAMID.bundle.id" -> "bundle.id"
          final String appId = appIdFull.contains('.')
              ? appIdFull.substring(appIdFull.indexOf('.') + 1)
              : appIdFull;
          final RunResult taskAllow = await _run(
              <String>['plutil', '-extract', 'Entitlements.get-task-allow', 'raw', '-o', '-', decoded.path]);
          final RunResult devices = await _run(
              <String>['plutil', '-extract', 'ProvisionedDevices', 'raw', '-o', '-', decoded.path]);
          final RunResult expiry = await _run(
              <String>['plutil', '-extract', 'ExpirationDate', 'raw', '-o', '-', decoded.path]);
          profiles.add(ProvisioningProfileInfo(
            path: entity.path,
            name: name,
            appId: appId,
            isAppStore: taskAllow.stdout.trim() == 'false' && devices.exitCode != 0,
            expiresAt: expiry.exitCode == 0
                ? DateTime.tryParse(expiry.stdout.trim())
                : null,
          ));
        } on ToolExit {
          continue; // Malformed profile — skip.
        }
      }
    }
    return profiles;
  }

  /// A valid "Apple Distribution" signing identity hash from the keychain.
  Future<String> findDistributionIdentity({String? override}) async {
    if (override != null && override.isNotEmpty) {
      return override;
    }
    final String out = await _runOrExit(
        <String>['security', 'find-identity', '-v', '-p', 'codesigning'],
        'Listing codesigning identities');
    for (final String line in out.split('\n')) {
      if (line.contains('Apple Distribution')) {
        final RegExpMatch? m = RegExp(r'([0-9A-F]{40})').firstMatch(line);
        if (m != null) {
          return m.group(1)!;
        }
      }
    }
    throwToolExit(
      'No "Apple Distribution" signing certificate found in the keychain.\n'
      'Create one in Xcode (Settings > Accounts > Manage Certificates) or at '
      'https://developer.apple.com/account/resources/certificates, then try again.',
    );
  }

  /// Extracts a profile's entitlements to a plist file for `codesign`.
  Future<File> extractEntitlements(String profilePath, File output) async {
    final File decoded = output.parent.childFile('${output.basename}.profile.plist');
    await _runOrExit(
        <String>['security', 'cms', '-D', '-i', profilePath, '-o', decoded.path],
        'Decoding provisioning profile');
    final String xml = await _runOrExit(
        <String>[_plistBuddy, '-x', '-c', 'Print :Entitlements', decoded.path],
        'Extracting entitlements');
    output.writeAsStringSync(xml);
    return output;
  }

  /// Re-identifies + re-signs the archived watch app for the store package.
  Future<void> resignWatchApp({
    required Directory watchApp,
    required String watchBundleId,
    required ProvisioningProfileInfo profile,
    required String identity,
    required Directory scratch,
  }) async {
    final String plist = watchApp.childFile('Info.plist').path;
    await _runOrExit(
        <String>[_plistBuddy, '-c', 'Set :CFBundleIdentifier $watchBundleId', plist],
        'Setting watch bundle id');
    // Watch-only apps must NOT carry a companion identifier (ITMS rejects it).
    await _run(<String>[_plistBuddy, '-c', 'Delete :WKCompanionAppBundleIdentifier', plist]);
    _fs.file(profile.path).copySync(watchApp.childFile('embedded.mobileprovision').path);
    final File ents = await extractEntitlements(
        profile.path, scratch.childFile('watch-entitlements.plist'));

    final Directory frameworks = watchApp.childDirectory('Frameworks');
    if (frameworks.existsSync()) {
      for (final FileSystemEntity f in frameworks.listSync()) {
        if (f is File && f.path.endsWith('.dylib')) {
          await _runOrExit(<String>['codesign', '--force', '--sign', identity, f.path],
              'Signing ${f.basename}');
        }
      }
    }
    await _runOrExit(
        <String>['codesign', '--force', '--sign', identity, '--entitlements', ents.path, watchApp.path],
        'Signing watch app');
  }

  /// Toolchain stamp keys for the container plist, read from the local Xcode.
  Future<Map<String, String>> toolchainStamps() async {
    final String sdkBuild = await _runOrExit(
        <String>['xcrun', '--sdk', 'iphoneos', '--show-sdk-build-version'], 'Reading iOS SDK build');
    final String sdkVersion = await _runOrExit(
        <String>['xcrun', '--sdk', 'iphoneos', '--show-sdk-version'], 'Reading iOS SDK version');
    final String xcodeVersionOut =
        await _runOrExit(<String>['xcodebuild', '-version'], 'Reading Xcode version');
    final String xcodeBuild = RegExp(r'Build version (\S+)').firstMatch(xcodeVersionOut)?.group(1) ?? '';
    final String xcodeVersion =
        RegExp(r'Xcode (\d+)\.(\d+)').firstMatch(xcodeVersionOut)?.groupCount == 2
            ? xcodeVersionOut.split('\n').first.replaceAll(RegExp(r'[^\d.]'), '')
            : '';
    final String osBuild =
        await _runOrExit(<String>['sw_vers', '-buildVersion'], 'Reading macOS build');
    // DTXcode format: "26.0" -> "2600".
    final List<String> parts = xcodeVersion.split('.');
    final dtXcode = parts.length >= 2
        ? '${parts[0]}${parts[1].padLeft(1, '0')}0'
        : '';
    return <String, String>{
      'BuildMachineOSBuild': osBuild,
      'DTCompiler': 'com.apple.compilers.llvm.clang.1_0',
      'DTPlatformBuild': sdkBuild,
      'DTPlatformName': 'iphoneos',
      'DTPlatformVersion': sdkVersion,
      'DTSDKBuild': sdkBuild,
      'DTSDKName': 'iphoneos$sdkVersion',
      'DTXcode': dtXcode,
      'DTXcodeBuild': xcodeBuild,
    };
  }

  /// Compiles the minimal iOS stub executable the container needs.
  Future<void> compileContainerStub(File output) async {
    final File source = output.parent.childFile('stub.c');
    source.writeAsStringSync('int main(void) { return 0; }\n');
    final String sdkPath = await _runOrExit(
        <String>['xcrun', '--sdk', 'iphoneos', '--show-sdk-path'], 'Locating iOS SDK');
    await _runOrExit(<String>[
      'xcrun', 'clang',
      '-arch', 'arm64',
      '-isysroot', sdkPath,
      '-miphoneos-version-min=15.0',
      source.path,
      '-o', output.path,
    ], 'Compiling container stub');
  }

  /// Builds and signs the full container, returning the Payload directory.
  Future<Directory> synthesizeContainer({
    required Directory archivedWatchApp,
    required String appName,
    required String containerBundleId,
    required String shortVersion,
    required String buildNumber,
    required ProvisioningProfileInfo hostProfile,
    required ProvisioningProfileInfo watchProfile,
    required String identity,
    required Directory workDir,
  }) async {
    final Directory payload = workDir.childDirectory('Payload')..createSync(recursive: true);
    // The .app directory name is cosmetic; the executable name must match
    // CFBundleExecutable. Derive a filesystem-safe name from the app name.
    final String executableName = appName.replaceAll(RegExp(r'[^A-Za-z0-9_.-]'), '');
    final Directory container = payload.childDirectory('$executableName.app')
      ..createSync(recursive: true);

    // Embedded watch app (copy, re-identify, re-sign).
    final Directory watchDir = container.childDirectory('Watch')..createSync();
    final Directory watchApp = watchDir.childDirectory(archivedWatchApp.basename);
    await _runOrExit(<String>['cp', '-R', archivedWatchApp.path, watchApp.path],
        'Copying watch app');
    await resignWatchApp(
      watchApp: watchApp,
      watchBundleId: '$containerBundleId.watchkitapp',
      profile: watchProfile,
      identity: identity,
      scratch: workDir,
    );

    // Container stub + metadata.
    await compileContainerStub(container.childFile(executableName));
    container.childFile('Info.plist').writeAsStringSync(containerInfoPlistXml(
          appName: appName,
          bundleId: containerBundleId,
          shortVersion: shortVersion,
          buildNumber: buildNumber,
          executableName: executableName,
          toolchainStamps: await toolchainStamps(),
        ));
    container.childFile('PkgInfo').writeAsStringSync('APPL????');
    _fs.file(hostProfile.path).copySync(container.childFile('embedded.mobileprovision').path);

    final File hostEnts = await extractEntitlements(
        hostProfile.path, workDir.childFile('host-entitlements.plist'));
    await _runOrExit(
        <String>['codesign', '--force', '--sign', identity, '--entitlements', hostEnts.path, container.path],
        'Signing container');
    await _runOrExit(
        <String>['codesign', '--verify', '--strict', '--deep', container.path],
        'Verifying container signature');
    return payload;
  }

  /// Zips [payload]'s parent into [output] (a standard .ipa).
  Future<File> packageIpa(Directory payload, File output) async {
    if (output.existsSync()) {
      output.deleteSync();
    }
    output.parent.createSync(recursive: true);
    final RunResult result = await _processUtils.run(
      <String>['zip', '-qr', output.path, 'Payload'],
      workingDirectory: payload.parent.path,
    );
    if (result.exitCode != 0) {
      throwToolExit('Packaging the ipa failed:\n${result.stderr}');
    }
    return output;
  }

  /// Reads CFBundle identity keys from an app bundle.
  Future<({String bundleId, String shortVersion, String buildNumber, String displayName})>
      readAppIdentity(Directory app) async {
    final String plist = app.childFile('Info.plist').path;
    return (
      bundleId: await _plutilRaw('CFBundleIdentifier', plist),
      shortVersion: await _plutilRaw('CFBundleShortVersionString', plist),
      buildNumber: await _plutilRaw('CFBundleVersion', plist),
      displayName: await _plutilRaw('CFBundleDisplayName', plist),
    );
  }

  /// Human guidance for a missing App Store profile.
  Never missingProfileExit(String bundleId) {
    throwToolExit(
      'No App Store provisioning profile found for "$bundleId".\n'
      'Create one at https://developer.apple.com/account/resources/profiles '
      '(type: App Store, App ID: $bundleId), download it, and double-click it '
      'so Xcode installs it — then run this command again.\n'
      'Profiles are searched in:\n'
      '  ~/Library/Developer/Xcode/UserData/Provisioning Profiles\n'
      '  ~/Library/MobileDevice/Provisioning Profiles',
    );
  }

  void printSummary(File ipa, String containerId, String version, String build) {
    _logger.printStatus('');
    _logger.printStatus('✓ Built App Store package: ${ipa.path}');
    _logger.printStatus('    $containerId  $version ($build)  watch-only container');
    _logger.printStatus('');
    _logger.printStatus('Next: flutter-watchos upload');
  }
}
