// Copyright 2026 The FlutterWatch Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter_tools/src/base/common.dart';
import 'package:flutter_tools/src/base/file_system.dart';
import 'package:flutter_tools/src/base/logger.dart';
import 'package:flutter_tools/src/base/process.dart';
import 'package:meta/meta.dart';

/// App Store packaging for standalone (watch-only) apps.
///
/// Xcode 26 removed App Store distribution of watch-only archives from
/// `xcodebuild -exportArchive` (only ad-hoc/enterprise/development methods are
/// offered) — the store packaging that Xcode Organizer performs interactively
/// is reproduced here instead, which is what makes a fully scripted
/// `flutter-watchos build ipa && flutter-watchos upload` possible.
///
/// A watch-only App Store package is an **iOS container** app. The layout
/// below byte-mirrors a package Apple accepted and released (Crown Breaker
/// 1.0.0) — deviations from it (bare dylibs instead of frameworks, a C stub
/// instead of a real host, adding SwiftSupport) have all drawn ITMS
/// processing rejections:
///
/// ```text
/// Payload/<AppName>.app/            real (launch-prohibited) SwiftUI iOS host
///   Info.plist                      ITSWatchOnlyContainer + LSApplicationLaunchProhibited
///   <host binary>                   compiled from watchos/HostApp/HostApp.swift
///   Assets.car, AppIcon*.png        compiled from watchos/HostApp/Assets.xcassets
///   embedded.mobileprovision        App Store profile for <container-id>
///   Watch/Runner.app                the real watch app
///     Info.plist                    CFBundleIdentifier = <container-id>.watchkitapp
///     Frameworks/Flutter.framework  engine, as a framework (never a bare dylib)
///     Frameworks/App.framework      Dart AOT code, as a framework
///     embedded.mobileprovision      App Store profile for <container-id>.watchkitapp
/// ```
///
/// The container's bundle id is the App Store Connect record; the embedded
/// watch app always uses `<container-id>.watchkitapp` (matching what Xcode
/// Organizer generates), regardless of which of the two forms the Xcode
/// project itself uses. Every plist key in [containerInfoPlistXml] was
/// dictated by App Store Connect validation errors — change with care and
/// re-validate with `flutter-watchos upload --validate-only`.

/// The App Store Connect record id for a watch app project bundle id: the
/// project may use either `com.acme.app` or `com.acme.app.watchkitapp`.
String containerBundleIdFor(String projectBundleId) {
  const suffix = '.watchkitapp';
  return projectBundleId.endsWith(suffix)
      ? projectBundleId.substring(0, projectBundleId.length - suffix.length)
      : projectBundleId;
}

/// The bundle id the embedded watch app must carry inside the store package.
String watchBundleIdFor(String projectBundleId) {
  return '${containerBundleIdFor(projectBundleId)}.watchkitapp';
}

String _xmlEscape(String s) => s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');

/// The Info.plist of the watch-only iOS container.
///
/// Keys are the minimum set App Store Connect validation accepts for a
/// watch-only submission (each one below was demanded by a 409 validation
/// error when absent):
///  - `ITSWatchOnlyContainer` + `LSApplicationLaunchProhibited`: required
///    when the embedded watch app has `WKWatchOnly = true`.
///  - `UIRequiredDeviceCapabilities [arm64]`: required for the 64-bit stub.
///  - `UIDeviceFamily [1, 2]`: store packages generated by Xcode Organizer
///    declare iPhone + iPad; declaring fewer families than a previously
///    shipped version is rejected ("must continue to support all devices").
///  - `DT*` / `BuildMachineOSBuild`: toolchain stamps; without them the
///    upload is rejected as built with an "unsupported SDK or Xcode".
String containerInfoPlistXml({
  required String appName,
  required String bundleId,
  required String shortVersion,
  required String buildNumber,
  required String executableName,
  required String minimumOSVersion,
  required bool hasIcons,
  required Map<String, String> toolchainStamps,
}) {
  final stamps = StringBuffer();
  final List<String> stampKeys = toolchainStamps.keys.toList()..sort();
  for (final key in stampKeys) {
    stamps.writeln(
        '\t<key>${_xmlEscape(key)}</key><string>${_xmlEscape(toolchainStamps[key]!)}</string>');
  }
  final icons = hasIcons
      ? '''
\t<key>CFBundleIcons</key>
\t<dict>
\t\t<key>CFBundlePrimaryIcon</key>
\t\t<dict>
\t\t\t<key>CFBundleIconFiles</key><array><string>AppIcon60x60</string></array>
\t\t\t<key>CFBundleIconName</key><string>AppIcon</string>
\t\t</dict>
\t</dict>
\t<key>CFBundleIcons~ipad</key>
\t<dict>
\t\t<key>CFBundlePrimaryIcon</key>
\t\t<dict>
\t\t\t<key>CFBundleIconFiles</key><array><string>AppIcon60x60</string><string>AppIcon76x76</string></array>
\t\t\t<key>CFBundleIconName</key><string>AppIcon</string>
\t\t</dict>
\t</dict>
'''
      : '';
  return '''
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
\t<key>CFBundleDevelopmentRegion</key><string>en</string>
\t<key>CFBundleDisplayName</key><string>${_xmlEscape(appName)}</string>
\t<key>CFBundleExecutable</key><string>${_xmlEscape(executableName)}</string>
${icons.trimRight().isEmpty ? '' : '${icons.trimRight()}\n'}\t<key>CFBundleIdentifier</key><string>${_xmlEscape(bundleId)}</string>
\t<key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
\t<key>CFBundleName</key><string>${_xmlEscape(executableName)}</string>
\t<key>CFBundlePackageType</key><string>APPL</string>
\t<key>CFBundleShortVersionString</key><string>${_xmlEscape(shortVersion)}</string>
\t<key>CFBundleSupportedPlatforms</key><array><string>iPhoneOS</string></array>
\t<key>CFBundleVersion</key><string>${_xmlEscape(buildNumber)}</string>
\t<key>ITSWatchOnlyContainer</key><true/>
\t<key>LSApplicationLaunchProhibited</key><true/>
\t<key>LSRequiresIPhoneOS</key><true/>
\t<key>MinimumOSVersion</key><string>${_xmlEscape(minimumOSVersion)}</string>
\t<key>UIApplicationSceneManifest</key><dict><key>UIApplicationSupportsMultipleScenes</key><false/></dict>
\t<key>UIDeviceFamily</key><array><integer>1</integer><integer>2</integer></array>
\t<key>UILaunchScreen</key><dict/>
\t<key>UIRequiredDeviceCapabilities</key><array><string>arm64</string></array>
\t<key>UISupportedInterfaceOrientations</key><array><string>UIInterfaceOrientationPortrait</string></array>
\t<key>UISupportedInterfaceOrientations~ipad</key><array><string>UIInterfaceOrientationPortrait</string><string>UIInterfaceOrientationPortraitUpsideDown</string><string>UIInterfaceOrientationLandscapeLeft</string><string>UIInterfaceOrientationLandscapeRight</string></array>
${stamps.toString().trimRight()}
</dict>
</plist>
''';
}

/// Swift standard-library dylib names referenced by `otool -L` output
/// (system `/usr/lib/swift/…` and `@rpath/…` references alike).
Set<String> swiftDylibsInOtoolOutput(String output) {
  return RegExp(r'(?:/usr/lib/swift/|@rpath/)(libswift[A-Za-z0-9_]+\.dylib)')
      .allMatches(output)
      .map((RegExpMatch m) => m.group(1)!)
      .toSet();
}

/// A parsed provisioning profile, as far as store packaging cares.
@immutable
class ProvisioningProfileInfo {
  const ProvisioningProfileInfo({
    required this.path,
    required this.name,
    required this.appId,
    required this.isAppStore,
    required this.expiresAt,
  });

  final String path;
  final String name;

  /// The bundle id the profile provisions (application-identifier minus the
  /// team prefix). `*` for wildcard profiles.
  final String appId;

  /// True for App Store distribution profiles: no device list and
  /// `get-task-allow = false`.
  final bool isAppStore;

  final DateTime? expiresAt;
}

/// Picks the best App Store profile for [bundleId]: exact app-id match,
/// unexpired, latest expiry wins.
ProvisioningProfileInfo? selectStoreProfile(
  List<ProvisioningProfileInfo> profiles,
  String bundleId, {
  DateTime? now,
}) {
  final DateTime cutoff = now ?? DateTime.now();
  final List<ProvisioningProfileInfo> candidates = profiles
      .where((ProvisioningProfileInfo p) =>
          p.isAppStore &&
          p.appId == bundleId &&
          (p.expiresAt == null || p.expiresAt!.isAfter(cutoff)))
      .toList()
    ..sort((ProvisioningProfileInfo a, ProvisioningProfileInfo b) {
      final DateTime ax = a.expiresAt ?? DateTime(9999);
      final DateTime bx = b.expiresAt ?? DateTime(9999);
      return bx.compareTo(ax);
    });
  return candidates.isEmpty ? null : candidates.first;
}

/// Orchestrates archive → re-sign → container synthesis → .ipa.
///
/// Everything here shells out to Apple tooling (`xcodebuild`, `codesign`,
/// `security`, `plutil`, `PlistBuddy`, `clang`, `zip`) — the pure decisions
/// live in the top-level helpers above so they stay unit-testable.
class WatchosIpaPackager {
  WatchosIpaPackager({
    required FileSystem fileSystem,
    required Logger logger,
    required ProcessUtils processUtils,
    required String homeDirPath,
  })  : _fs = fileSystem,
        _logger = logger,
        _processUtils = processUtils,
        _home = homeDirPath;

  final FileSystem _fs;
  final Logger _logger;
  final ProcessUtils _processUtils;
  final String _home;

  static const String _plistBuddy = '/usr/libexec/PlistBuddy';

  Future<RunResult> _run(List<String> cmd) => _processUtils.run(cmd);

  Future<String> _runOrExit(List<String> cmd, String what) async {
    final RunResult result = await _run(cmd);
    if (result.exitCode != 0) {
      throwToolExit('$what failed:\n${result.stderr}\n${result.stdout}');
    }
    return result.stdout.trim();
  }

  Future<String> _plutilRaw(String keyPath, String plistPath) =>
      _runOrExit(<String>['plutil', '-extract', keyPath, 'raw', '-o', '-', plistPath],
          'Reading $keyPath from $plistPath');

  /// The provisioning-profile directories Xcode uses (new location first).
  List<Directory> profileDirectories() => <Directory>[
        _fs.directory(_fs.path.join(
            _home, 'Library', 'Developer', 'Xcode', 'UserData', 'Provisioning Profiles')),
        _fs.directory(
            _fs.path.join(_home, 'Library', 'MobileDevice', 'Provisioning Profiles')),
      ];

  /// Decodes and indexes every local provisioning profile.
  Future<List<ProvisioningProfileInfo>> scanProfiles(Directory scratch) async {
    final profiles = <ProvisioningProfileInfo>[];
    for (final Directory dir in profileDirectories()) {
      if (!dir.existsSync()) {
        continue;
      }
      for (final FileSystemEntity entity in dir.listSync()) {
        if (entity is! File || !entity.path.endsWith('.mobileprovision')) {
          continue;
        }
        final File decoded = scratch.childFile('${entity.basename}.plist');
        final RunResult decode =
            await _run(<String>['security', 'cms', '-D', '-i', entity.path, '-o', decoded.path]);
        if (decode.exitCode != 0 || !decoded.existsSync()) {
          continue; // Unreadable profile — skip, never fatal.
        }
        try {
          final String name = await _plutilRaw('Name', decoded.path);
          final String appIdFull =
              await _plutilRaw('Entitlements.application-identifier', decoded.path);
          // "TEAMID.bundle.id" -> "bundle.id"
          final String appId = appIdFull.contains('.')
              ? appIdFull.substring(appIdFull.indexOf('.') + 1)
              : appIdFull;
          final RunResult taskAllow = await _run(
              <String>['plutil', '-extract', 'Entitlements.get-task-allow', 'raw', '-o', '-', decoded.path]);
          final RunResult devices = await _run(
              <String>['plutil', '-extract', 'ProvisionedDevices', 'raw', '-o', '-', decoded.path]);
          final RunResult expiry = await _run(
              <String>['plutil', '-extract', 'ExpirationDate', 'raw', '-o', '-', decoded.path]);
          profiles.add(ProvisioningProfileInfo(
            path: entity.path,
            name: name,
            appId: appId,
            isAppStore: taskAllow.stdout.trim() == 'false' && devices.exitCode != 0,
            expiresAt: expiry.exitCode == 0
                ? DateTime.tryParse(expiry.stdout.trim())
                : null,
          ));
        } on ToolExit {
          continue; // Malformed profile — skip.
        }
      }
    }
    return profiles;
  }

  /// A valid "Apple Distribution" signing identity hash from the keychain.
  Future<String> findDistributionIdentity({String? override}) async {
    if (override != null && override.isNotEmpty) {
      return override;
    }
    final String out = await _runOrExit(
        <String>['security', 'find-identity', '-v', '-p', 'codesigning'],
        'Listing codesigning identities');
    for (final String line in out.split('\n')) {
      if (line.contains('Apple Distribution')) {
        final RegExpMatch? m = RegExp(r'([0-9A-F]{40})').firstMatch(line);
        if (m != null) {
          return m.group(1)!;
        }
      }
    }
    throwToolExit(
      'No "Apple Distribution" signing certificate found in the keychain.\n'
      'Create one in Xcode (Settings > Accounts > Manage Certificates) or at '
      'https://developer.apple.com/account/resources/certificates, then try again.',
    );
  }

  /// Extracts a profile's entitlements to a plist file for `codesign`.
  Future<File> extractEntitlements(String profilePath, File output) async {
    final File decoded = output.parent.childFile('${output.basename}.profile.plist');
    await _runOrExit(
        <String>['security', 'cms', '-D', '-i', profilePath, '-o', decoded.path],
        'Decoding provisioning profile');
    final String xml = await _runOrExit(
        <String>[_plistBuddy, '-x', '-c', 'Print :Entitlements', decoded.path],
        'Extracting entitlements');
    output.writeAsStringSync(xml);
    return output;
  }

  /// Re-identifies + re-signs the archived watch app for the store package.
  Future<void> resignWatchApp({
    required Directory watchApp,
    required String watchBundleId,
    required ProvisioningProfileInfo profile,
    required String identity,
    required Directory scratch,
  }) async {
    final String plist = watchApp.childFile('Info.plist').path;
    await _runOrExit(
        <String>[_plistBuddy, '-c', 'Set :CFBundleIdentifier $watchBundleId', plist],
        'Setting watch bundle id');
    // Watch-only apps must NOT carry a companion identifier (ITMS rejects it).
    await _run(<String>[_plistBuddy, '-c', 'Delete :WKCompanionAppBundleIdentifier', plist]);
    _fs.file(profile.path).copySync(watchApp.childFile('embedded.mobileprovision').path);
    final File ents = await extractEntitlements(
        profile.path, scratch.childFile('watch-entitlements.plist'));

    final Directory frameworks = watchApp.childDirectory('Frameworks');
    if (frameworks.existsSync()) {
      for (final FileSystemEntity f in frameworks.listSync()) {
        if (f is Directory && f.path.endsWith('.framework')) {
          await _runOrExit(<String>['codesign', '--force', '--sign', identity, f.path],
              'Signing ${f.basename}');
        }
      }
    }
    await _runOrExit(
        <String>['codesign', '--force', '--sign', identity, '--entitlements', ents.path, watchApp.path],
        'Signing watch app');
  }

  /// Framework Info.plist for a wrapped engine/app library.
  String _frameworkInfoPlist({
    required String executable,
    required String bundleId,
    required String minimumOSVersion,
  }) {
    return '''
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
\t<key>CFBundleExecutable</key><string>$executable</string>
\t<key>CFBundleIdentifier</key><string>$bundleId</string>
\t<key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
\t<key>CFBundleName</key><string>$executable</string>
\t<key>CFBundlePackageType</key><string>FMWK</string>
\t<key>CFBundleShortVersionString</key><string>1.0</string>
\t<key>CFBundleSupportedPlatforms</key><array><string>WatchOS</string></array>
\t<key>CFBundleVersion</key><string>1</string>
\t<key>MinimumOSVersion</key><string>$minimumOSVersion</string>
</dict>
</plist>
''';
  }

  /// Repackages the watch app's bare dylibs as proper framework bundles —
  /// `Frameworks/libflutter_engine.dylib` becomes
  /// `Frameworks/Flutter.framework/Flutter` and `Frameworks/App.dylib`
  /// becomes `Frameworks/App.framework/App` — and repoints the Runner
  /// binary's engine load command.
  ///
  /// App Store packages must not contain bare dylibs; the engine's App
  /// loader probes both `Frameworks/App.dylib` and
  /// `Frameworks/App.framework/App`, so this is runtime-safe.
  Future<void> wrapDylibsAsFrameworks({
    required Directory watchApp,
    required String watchBundleId,
    required String minimumOSVersion,
  }) async {
    final Directory frameworks = watchApp.childDirectory('Frameworks');
    const wraps = <(String, String, String)>[
      ('libflutter_engine.dylib', 'Flutter', 'flutterfw'),
      ('App.dylib', 'App', 'appfw'),
    ];
    for (final (String dylibName, String fwName, String idSuffix) in wraps) {
      final File dylib = frameworks.childFile(dylibName);
      if (!dylib.existsSync()) {
        continue;
      }
      final Directory fw = frameworks.childDirectory('$fwName.framework')
        ..createSync(recursive: true);
      final File binary = fw.childFile(fwName);
      dylib.renameSync(binary.path);
      await _runOrExit(
          <String>['install_name_tool', '-id', '@rpath/$fwName.framework/$fwName', binary.path],
          'Setting $fwName.framework install name');
      fw.childFile('Info.plist').writeAsStringSync(_frameworkInfoPlist(
            executable: fwName,
            bundleId: '$watchBundleId.$idSuffix',
            minimumOSVersion: minimumOSVersion,
          ));
    }
    // The Runner binary links the engine by its old dylib name.
    final File runner = watchApp.childFile('Runner');
    if (runner.existsSync()) {
      await _runOrExit(<String>[
        'install_name_tool', '-change',
        '@rpath/libflutter_engine.dylib', '@rpath/Flutter.framework/Flutter',
        runner.path,
      ], 'Repointing Runner engine load command');
    }
  }

  /// Compiles the (launch-prohibited) iOS host app binary.
  ///
  /// Uses the project's `watchos/HostApp/HostApp.swift` when present so apps
  /// can brand the host screen; otherwise a generic SwiftUI host is
  /// generated. Also compiles `HostApp/Assets.xcassets` (app icons) with
  /// actool when present; returns true when icons were produced.
  Future<bool> buildHostApp({
    required Directory container,
    required String executableName,
    required String appName,
    required Directory? hostAppDir,
    required String minimumOSVersion,
    required Directory scratch,
  }) async {
    final String sdkPath = await _runOrExit(
        <String>['xcrun', '--sdk', 'iphoneos', '--show-sdk-path'], 'Locating iOS SDK');

    File source;
    if (hostAppDir != null && hostAppDir.childFile('HostApp.swift').existsSync()) {
      source = hostAppDir.childFile('HostApp.swift');
    } else {
      source = scratch.childFile('HostApp.swift');
      source.writeAsStringSync('''
import SwiftUI

// Minimal iOS host: App Store watch-only submissions ship inside an iOS
// container app. This host is never launched (LSApplicationLaunchProhibited).
@main
struct GeneratedHostApp: App {
  var body: some Scene {
    WindowGroup {
      VStack(spacing: 16) {
        Image(systemName: "applewatch").font(.system(size: 64))
        Text("$appName").font(.title.bold())
        Text("This app runs on Apple Watch.").foregroundStyle(.secondary)
      }
    }
  }
}
''');
    }
    await _runOrExit(<String>[
      'xcrun', 'swiftc',
      '-sdk', sdkPath,
      '-target', 'arm64-apple-ios$minimumOSVersion',
      '-parse-as-library', '-O',
      source.path,
      '-o', container.childFile(executableName).path,
    ], 'Compiling host app');

    final Directory? assets = hostAppDir?.childDirectory('Assets.xcassets');
    if (assets == null || !assets.existsSync()) {
      return false;
    }
    await _runOrExit(<String>[
      'xcrun', 'actool',
      '--compile', container.path,
      '--platform', 'iphoneos',
      '--minimum-deployment-target', minimumOSVersion,
      '--app-icon', 'AppIcon',
      '--output-partial-info-plist', scratch.childFile('actool-partial.plist').path,
      assets.path,
    ], 'Compiling host app icons');
    return true;
  }

  /// Toolchain stamp keys for the container plist, read from the local Xcode.
  Future<Map<String, String>> toolchainStamps() async {
    final String sdkBuild = await _runOrExit(
        <String>['xcrun', '--sdk', 'iphoneos', '--show-sdk-build-version'], 'Reading iOS SDK build');
    final String sdkVersion = await _runOrExit(
        <String>['xcrun', '--sdk', 'iphoneos', '--show-sdk-version'], 'Reading iOS SDK version');
    final String xcodeVersionOut =
        await _runOrExit(<String>['xcodebuild', '-version'], 'Reading Xcode version');
    final String xcodeBuild = RegExp(r'Build version (\S+)').firstMatch(xcodeVersionOut)?.group(1) ?? '';
    final String xcodeVersion =
        RegExp(r'Xcode (\d+)\.(\d+)').firstMatch(xcodeVersionOut)?.groupCount == 2
            ? xcodeVersionOut.split('\n').first.replaceAll(RegExp(r'[^\d.]'), '')
            : '';
    final String osBuild =
        await _runOrExit(<String>['sw_vers', '-buildVersion'], 'Reading macOS build');
    // DTXcode format: "26.0" -> "2600".
    final List<String> parts = xcodeVersion.split('.');
    final dtXcode = parts.length >= 2
        ? '${parts[0]}${parts[1].padLeft(1, '0')}0'
        : '';
    return <String, String>{
      'BuildMachineOSBuild': osBuild,
      'DTCompiler': 'com.apple.compilers.llvm.clang.1_0',
      'DTPlatformBuild': sdkBuild,
      'DTPlatformName': 'iphoneos',
      'DTPlatformVersion': sdkVersion,
      'DTSDKBuild': sdkBuild,
      'DTSDKName': 'iphoneos$sdkVersion',
      'DTXcode': dtXcode,
      'DTXcodeBuild': xcodeBuild,
    };
  }

  /// Builds and signs the full container, returning the Payload directory.
  Future<Directory> synthesizeContainer({
    required Directory archivedWatchApp,
    required String appName,
    required String containerBundleId,
    required String shortVersion,
    required String buildNumber,
    required String minimumOSVersion,
    required ProvisioningProfileInfo hostProfile,
    required ProvisioningProfileInfo watchProfile,
    required String identity,
    required Directory workDir,
    Directory? hostAppDir,
  }) async {
    final Directory payload = workDir.childDirectory('Payload')..createSync(recursive: true);
    // The .app directory name is cosmetic; the executable name must match
    // CFBundleExecutable. Derive a filesystem-safe name from the app name.
    final String executableName = appName.replaceAll(RegExp(r'[^A-Za-z0-9_.-]'), '');
    final Directory container = payload.childDirectory('$executableName.app')
      ..createSync(recursive: true);
    final watchBundleId = '$containerBundleId.watchkitapp';

    // Embedded watch app (copy, frameworks, re-identify, re-sign).
    final Directory watchDir = container.childDirectory('Watch')..createSync();
    final Directory watchApp = watchDir.childDirectory(archivedWatchApp.basename);
    await _runOrExit(<String>['cp', '-R', archivedWatchApp.path, watchApp.path],
        'Copying watch app');
    await wrapDylibsAsFrameworks(
      watchApp: watchApp,
      watchBundleId: watchBundleId,
      minimumOSVersion: minimumOSVersion,
    );
    await resignWatchApp(
      watchApp: watchApp,
      watchBundleId: watchBundleId,
      profile: watchProfile,
      identity: identity,
      scratch: workDir,
    );

    // Host app + metadata.
    final bool hasIcons = await buildHostApp(
      container: container,
      executableName: executableName,
      appName: appName,
      hostAppDir: hostAppDir,
      minimumOSVersion: minimumOSVersion,
      scratch: workDir,
    );
    container.childFile('Info.plist').writeAsStringSync(containerInfoPlistXml(
          appName: appName,
          bundleId: containerBundleId,
          shortVersion: shortVersion,
          buildNumber: buildNumber,
          executableName: executableName,
          minimumOSVersion: minimumOSVersion,
          hasIcons: hasIcons,
          toolchainStamps: await toolchainStamps(),
        ));
    container.childFile('PkgInfo').writeAsStringSync('APPL????');
    _fs.file(hostProfile.path).copySync(container.childFile('embedded.mobileprovision').path);

    final File hostEnts = await extractEntitlements(
        hostProfile.path, workDir.childFile('host-entitlements.plist'));
    await _runOrExit(
        <String>['codesign', '--force', '--sign', identity, '--entitlements', hostEnts.path, container.path],
        'Signing container');
    await _runOrExit(
        <String>['codesign', '--verify', '--strict', '--deep', container.path],
        'Verifying container signature');
    return payload;
  }

  /// Zips [payload] into [output] — a standard .ipa.
  ///
  /// Deliberately no SwiftSupport folder: the accepted reference package
  /// ships without one (min watchOS >= 6 is ABI-stable), and adding one
  /// draws ITMS-90428.
  Future<File> packageIpa(Directory payload, File output) async {
    if (output.existsSync()) {
      output.deleteSync();
    }
    output.parent.createSync(recursive: true);
    final RunResult result = await _processUtils.run(
      <String>['zip', '-qr', output.path, 'Payload'],
      workingDirectory: payload.parent.path,
    );
    if (result.exitCode != 0) {
      throwToolExit('Packaging the ipa failed:\n${result.stderr}');
    }
    return output;
  }

  /// Reads CFBundle identity keys from an app bundle.
  Future<({String bundleId, String shortVersion, String buildNumber, String displayName})>
      readAppIdentity(Directory app) async {
    final String plist = app.childFile('Info.plist').path;
    return (
      bundleId: await _plutilRaw('CFBundleIdentifier', plist),
      shortVersion: await _plutilRaw('CFBundleShortVersionString', plist),
      buildNumber: await _plutilRaw('CFBundleVersion', plist),
      displayName: await _plutilRaw('CFBundleDisplayName', plist),
    );
  }

  /// The watch app's MinimumOSVersion, or null when unreadable.
  Future<String?> readMinimumOSVersion(Directory app) async {
    final RunResult result = await _run(<String>[
      'plutil', '-extract', 'MinimumOSVersion', 'raw', '-o', '-',
      app.childFile('Info.plist').path,
    ]);
    return result.exitCode == 0 ? result.stdout.trim() : null;
  }

  /// Human guidance for a missing App Store profile.
  Never missingProfileExit(String bundleId) {
    throwToolExit(
      'No App Store provisioning profile found for "$bundleId".\n'
      'Create one at https://developer.apple.com/account/resources/profiles '
      '(type: App Store, App ID: $bundleId), download it, and double-click it '
      'so Xcode installs it — then run this command again.\n'
      'Profiles are searched in:\n'
      '  ~/Library/Developer/Xcode/UserData/Provisioning Profiles\n'
      '  ~/Library/MobileDevice/Provisioning Profiles',
    );
  }

  void printSummary(File ipa, String containerId, String version, String build) {
    _logger.printStatus('');
    _logger.printStatus('✓ Built App Store package: ${ipa.path}');
    _logger.printStatus('    $containerId  $version ($build)  watch-only container');
    _logger.printStatus('');
    _logger.printStatus('Next: flutter-watchos upload');
  }
}
