// Copyright 2026 The FlutterWatch Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter_tools/src/base/file_system.dart';
import 'package:meta/meta.dart';

// Rendered manifests intentionally start with `// swift-tools-version:` (which
// must be the first line of a Package.swift), not a blank line.
// ignore_for_file: leading_newlines_in_multiline_strings

/// Generates the Swift Package Manager packages a watchOS app build needs to
/// consume federated `*_watchos` plugins (Flutter 3.44+ default), mirroring how
/// stock Flutter wires SPM for iOS/macOS — but reimplemented here because the
/// upstream orchestration (`FlutterDarwinPlatform`) only knows iOS/macOS and we
/// don't patch the SDK.
///
/// Two generated packages, written under `watchos/Flutter/ephemeral/Packages/`:
///
/// 1. **`FlutterFramework`** — wraps the watchOS `Flutter.xcframework` as a
///    SwiftPM `.binaryTarget`. Once this is in the resolved package graph, the
///    `Flutter` module becomes importable by every plugin target in the build —
///    which is why federated plugins declare no Flutter dependency of their own.
///
/// 2. **`FlutterGeneratedPluginSwiftPackage`** — the umbrella. Its single target
///    depends on `FlutterFramework` plus each discovered plugin's product, so
///    linking the umbrella into Runner pulls in every plugin (and Flutter). The
///    product is `static` so the plugins' symbols land in the Runner binary.
///
/// This is a pure generator: it only writes manifests and symlinks.
class WatchosSwiftPackageManager {
  WatchosSwiftPackageManager({required FileSystem fileSystem}) : _fs = fileSystem;

  final FileSystem _fs;

  /// Name of the umbrella package/target, matching stock Flutter so the Xcode
  /// integration objects line up.
  static const String kGeneratedPluginsPackageName = 'FlutterGeneratedPluginSwiftPackage';

  /// Name of the package/target that vends `Flutter.xcframework`.
  static const String kFlutterFrameworkPackageName = 'FlutterFramework';

  /// watchOS deployment floor the generated packages declare. Must be ≤ the
  /// app's `WATCHOS_DEPLOYMENT_TARGET` or SwiftPM rejects the dependency graph.
  static const String kDefaultDeploymentTarget = '7.0';

  /// Writes the `FlutterFramework` package into [packageDirectory] and symlinks
  /// [xcframework] inside it (binary targets must reference a local path).
  void generateFlutterFrameworkPackage({
    required Directory packageDirectory,
    required Directory xcframework,
  }) {
    packageDirectory.createSync(recursive: true);
    packageDirectory
        .childFile('Package.swift')
        .writeAsStringSync(renderFlutterFrameworkManifest());

    final Link link = packageDirectory.childLink(xcframework.basename);
    if (link.existsSync()) {
      link.deleteSync();
    }
    link.createSync(xcframework.absolute.path);
  }

  /// Writes the `FlutterGeneratedPluginSwiftPackage` umbrella into
  /// [packageDirectory], symlinking each plugin under `.packages/<name>` and
  /// depending on [flutterFrameworkRelativePath] (the path to the
  /// `FlutterFramework` package, relative to [packageDirectory]).
  String generatePluginsSwiftPackage({
    required Directory packageDirectory,
    required List<WatchosSpmPlugin> plugins,
    required String flutterFrameworkRelativePath,
    String deploymentTarget = kDefaultDeploymentTarget,
  }) {
    packageDirectory.createSync(recursive: true);

    final Directory sources = packageDirectory
        .childDirectory('Sources')
        .childDirectory(kGeneratedPluginsPackageName);
    sources.createSync(recursive: true);
    sources.childFile('$kGeneratedPluginsPackageName.swift').writeAsStringSync(
      '// Generated by flutter-watchos. This package brings together the watchOS\n'
      '// implementations of every federated plugin the app depends on.\n',
    );

    final Directory packagesDir = packageDirectory.childDirectory('.packages');
    packagesDir.createSync(recursive: true);
    final pluginRefs = <_PluginRef>[];
    for (final WatchosSpmPlugin plugin in plugins) {
      final Link link = packagesDir.childLink(plugin.name);
      if (link.existsSync()) {
        link.deleteSync();
      }
      link.createSync(_fs.directory(plugin.packagePath).absolute.path);
      pluginRefs.add(
        _PluginRef(
          name: plugin.name,
          relativePath: '.packages/${plugin.name}',
          productName: plugin.libraryName,
        ),
      );
    }

    final String manifest = renderPluginsUmbrellaManifest(
      plugins: pluginRefs,
      flutterFrameworkRelativePath: flutterFrameworkRelativePath,
      deploymentTarget: deploymentTarget,
    );
    packageDirectory.childFile('Package.swift').writeAsStringSync(manifest);
    return manifest;
  }

  /// Renders the `FlutterFramework` package manifest.
  @visibleForTesting
  static String renderFlutterFrameworkManifest() {
    return '''// swift-tools-version: 5.9
// Generated by flutter-watchos. Do not edit.
//
// Vends the watchOS Flutter engine (Flutter.xcframework) to the Swift package
// graph so federated plugin targets can `import Flutter` without declaring a
// dependency of their own.
import PackageDescription

let package = Package(
  name: "$kFlutterFrameworkPackageName",
  products: [
    .library(name: "$kFlutterFrameworkPackageName", targets: ["$kFlutterFrameworkPackageName"]),
  ],
  targets: [
    .binaryTarget(name: "$kFlutterFrameworkPackageName", path: "Flutter.xcframework"),
  ]
)
''';
  }

  /// Renders the umbrella `FlutterGeneratedPluginSwiftPackage` manifest.
  ///
  /// SwiftPM derives a dynamic library's `CFBundleIdentifier` from the product
  /// name and rejects underscores, so plugin *product* names are hyphenated
  /// (e.g. `shared_preferences_watchos` → `shared-preferences-watchos`),
  /// matching the library name federated plugins declare. The package name
  /// (used for the path dependency) keeps the underscores.
  @visibleForTesting
  static String renderPluginsUmbrellaManifest({
    required List<_PluginRef> plugins,
    required String flutterFrameworkRelativePath,
    String deploymentTarget = kDefaultDeploymentTarget,
  }) {
    final dependencies = <String>[
      '    .package(name: "$kFlutterFrameworkPackageName", path: "$flutterFrameworkRelativePath"),',
      for (final _PluginRef p in plugins)
        '    .package(name: "${p.name}", path: "${p.relativePath}"),',
    ];
    final targetDependencies = <String>[
      '        .product(name: "$kFlutterFrameworkPackageName", package: "$kFlutterFrameworkPackageName"),',
      for (final _PluginRef p in plugins)
        '        .product(name: "${p.productName}", package: "${p.name}"),',
    ];
    return '''// swift-tools-version: 5.9
// Generated by flutter-watchos. Do not edit.
import PackageDescription

let package = Package(
  name: "$kGeneratedPluginsPackageName",
  platforms: [
    .watchOS("$deploymentTarget"),
  ],
  products: [
    .library(name: "$kGeneratedPluginsPackageName", type: .static, targets: ["$kGeneratedPluginsPackageName"]),
  ],
  dependencies: [
${dependencies.join('\n')}
  ],
  targets: [
    .target(
      name: "$kGeneratedPluginsPackageName",
      dependencies: [
${targetDependencies.join('\n')}
      ]
    ),
  ]
)
''';
  }
}

/// A federated watchOS plugin to include in the umbrella package: its [name]
/// (matching the SwiftPM package name in its `watchos/Package.swift`), the
/// [libraryName] (the `.library(name:)` product the umbrella links), and the
/// path to the directory containing that `Package.swift`.
@immutable
class WatchosSpmPlugin {
  WatchosSpmPlugin({required this.name, required this.packagePath, String? libraryName})
    : libraryName = libraryName ?? name.replaceAll('_', '-');

  final String name;
  final String packagePath;

  /// The SwiftPM product name the umbrella references. Defaults to the
  /// hyphenated package name (the porter convention).
  final String libraryName;
}

/// Internal: a resolved plugin reference for manifest rendering.
@immutable
class _PluginRef {
  const _PluginRef({required this.name, required this.relativePath, required this.productName});

  final String name;
  final String relativePath;

  /// SwiftPM product (library) name the umbrella links against.
  final String productName;
}
